---
#### This task file creates a user, two groups, updates apt cache and installs build dependencies
- name: Update apt cache
  apt: update_cache=yes

- name: Create nagcmd and nagios Groups
  group: name="{{ item }}" state=present
  with_items:
    - "{{ nagcmd_group }}"
    - "{{ nagios_group }}"
  tags:
    - group

- name: Create nagios User and add to nagcmd Group
  user: name={{ user }} group={{ nagcmd_group }}
  tags:
    - group



- name: Update repo cache and install build dependencies
  apt: name={{ item }} state=present force=yes
  with_items:
    - autoconf 
    - gcc 
    - libc6 
    - make 
    - wget 
    - unzip 
    - apache2 
    - php 
    - libapache2-mod-php7.4 
    - libgd-dev
    - apache2
  tags:
    - build_setup