---
- hosts: all
  user: "{{ server_user }}"
  become: yes
  become_method: sudo
  vars_files:
  - vars.yml
  roles:
    - nagios-defaults
    - nagios-install
    - nagios-plugins
    - configure-nagios
    - add-host